services:
  - type: web
    name: campus-parking-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
